### PR TITLE
CMParts: Battery light: 100% charged level

### PR DESCRIPTION
**Pull request by niko-yanev**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Settings.System.BATTERY_LIGHT_REALLY_FULL_COLOR 
Is this defined in base?

**Comment by niko-yanev** [comment]
i think so, we can try ;)

**Comment by niko-yanev** [comment]
But all of the 3 patches should be merged

**Comment by neobuddy89** [comment]
No, it's not defined in base.
This will just end with compilation error.

**Comment by niko-yanev** [comment]
So can't somebody define it?

**Comment by neobuddy89** [comment]
1. Merge request should be in 1 commit - not 3 different patches - to maintain clean code history and easy adaptability for future.
2. All dependent code (like for base) should be provided. No partial code.
3. Test before pulling request.

**Comment by neobuddy89** [comment]
4. Commit should be with original authorship.

We are happy that you contributed and aren't trying to be disrespectful.
But need to follow proper protocol to ensure bug-free feature.

**Pull request closed without merging**
